puzzle: samegame
params: 5x5c3s2
obs_type: puzzle_state # puzzle_state | rgb
render_mode: rgb_array
window_width: 128
window_height: 128
allow_undo: false
max_state_repeats: 200
include_cursor_in_state_info: true
