defaults:
  - default
  - experiment: samegame_5x5c3s2_cnn
  - _self_
  - override hydra/sweeper: optuna

mode: train
experiment_name: sweep_cnn_samegame5x5c3s2_${hydra:job.num}

training:
  optimize_metric: avg_return

hydra:
  mode: MULTIRUN
  sweeper:
    direction: maximize
    study_name: samegame_5x5c3s2_cnn
    storage: sqlite:///${hydra:runtime.cwd}/optuna/hypersearch.db
    n_trials: 80
    n_jobs: 1
    search_space:
      seed:
        type: categorical
        choices: [11, 23, 37, 41, 53]
      agent.learning_rate:
        type: float
        low: 1e-5
        high: 5e-4
        log: true
      agent.gamma:
        type: float
        low: 0.95
        high: 0.999
      agent.batch_size:
        type: categorical
        choices: [32, 64]
      agent.buffer_size:
        type: categorical
        choices: [300000, 500000, 800000]
      agent.learning_starts:
        type: categorical
        choices: [100000, 300000, 500000]
      agent.target_update_interval:
        type: categorical
        choices: [2000, 5000, 10000]
      agent.exploration_decay:
        type: categorical
        choices: [500000, 750000, 1000000, 1500000]
      agent.exploration_final_eps:
        type: float
        low: 0.01
        high: 0.10
      agent.train_freq:
        type: categorical
        choices: [2, 4, 8]
      agent.gradient_steps:
        type: categorical
        choices: [1, 2]
