type: cnn
conv_channels:
  - 32
  - 64
  - 64
conv_kernels:
  - 8
  - 4
  - 3
conv_strides:
  - 4
  - 2
  - 1
fc_hidden: 512
batch_size: 32
gamma: 0.99
eps_start: 0.9
eps_end: 0.05
eps_decay: 100000
tau: 0.005
lr: 1.0e-5
buffer_size: 10000
replay_buffer_type: standard # standard | her
her_n_sampled_goal: 4
her_goal_selection_strategy: future # future | final | episode
her_goal_tolerance: 1.0e-6
